FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Nsi/Nsi.Api.csproj", "Nsi/"]
COPY ["Nsi.Infrastructure/Nsi.Infrastructure.csproj", "Nsi.Infrastructure/"]
COPY ["Nsi.Application/Nsi.Application.csproj", "Nsi.Application/"]
COPY ["Nsi.Domain/Nsi.Domain.csproj", "Nsi.Domain/"]
RUN dotnet restore "Nsi/Nsi.Api.csproj"
COPY . .
WORKDIR "/src/Nsi"
RUN dotnet build "Nsi.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Nsi.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Nsi.Api.dll"]